### PR TITLE
fix: serialize command to json

### PR DESCRIPTION
**Pull request by DoctorApparatus**
As you can see at https://docs.rs/tauri/2.0.0-beta.22/tauri/ipc/enum.InvokeBody.html defines the types needed for anything that gets "sent" via "Channel" in spawn

### CODE REVIEW

**Comment by HuakunShen** [comment]
@DoctorApparatus What is the difference and use case of this update? I didn't see a difference in output.
The current code is the same as the original shell plugin.

**Comment by DoctorApparatus** [comment]
```rust
error[E0308]: mismatched types
   --> src/commands.rs:289:30
    |
289 |             if on_event.send(&js_event).is_err() {
    |                         ---- ^^^^^^^^^ expected `InvokeBody`, found `&JSCommandEvent`
    |                         |
    |                         arguments to this method are incorrect
    |
note: method defined here
   --> /home/doctorapparatus/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.24/src/ipc/channel.rs:194:10
    |
194 |   pub fn send(&self, data: TSend) -> crate::Result<()>
    |          ^^^^

error[E0308]: mismatched types
   --> src/commands.rs:296:42
    |
296 |                         if on_event.send(js_event).is_err() {
    |                                     ---- ^^^^^^^^ expected `InvokeBody`, found `&JSCommandEvent`
    |                                     |
    |                                     arguments to this method are incorrect
    |
```

When compiling with the latest tauri versions I've had the following compilation error.

**Comment by HuakunShen** [comment]
I see. What version of Tauri are you using?
They just published new versions of the original shell plugin. I will fix it if it's not compatible with the latest version.

**Comment by HuakunShen** [comment]
Error fixed in release v2.0.8 https://github.com/HuakunShen/tauri-plugin-shellx/releases/tag/v2.0.8

See commit https://github.com/HuakunShen/tauri-plugin-shellx/commit/867a03f7001988faa9dad63e441aa8346e8aa1aa

Updated code is from https://github.com/tauri-apps/plugins-workspace/blob/93bdb6d133b89d990ddd5470536edfe4cb617e89/plugins/shell/src/commands.rs#L236

Had to update spawn command code: `on_event: Channel` -> `on_event: Channel<JSCommandEvent>`

**Pull request closed without merging**
